query GetAssignedAudits($userId: Int) {
	audit(
		where: { closedAt: { _is_null: true }, auditorId: { _eq: $userId } }
		order_by: { endAt: asc }
	) {
		id
		private {
			code
		}
		endAt
		updatedAt
		group {
			path
			captainLogin
			members {
				user {
					login
					avatarUrl
					id
				}
			}
		}
	}
}
