query GetEventChildren($eventId: Int, $offset: Int, $limit: Int) {
	childEvents: event(
		where: { parentId: { _eq: $eventId } }
		order_by: { endAt: desc }
		offset: $offset
		limit: $limit
	) {
		...EventFields
	}
}
