query GetUserGroupsByLogin($userLogin: String, $offset: Int, $limit: Int) {
	group_user(
		where: { userLogin: { _eq: $userLogin }, accepted: { _eq: true } }
		offset: $offset
		limit: $limit
		order_by: { group: { auditors_aggregate: { max: { createdAt: desc_nulls_last } } } }
	) {
		...UserGroupFields
	}
}
