fragment UserGroupFields on group_user {
	id
	userLogin
	userId
	group {
		captainId
		captainLogin
		path
		members {
			id
			user {
				...PublicUserFields
			}
		}
		auditors {
			id
			closedAt
			closureType
			auditor {
				...PublicUserFields
			}
		}
	}
}
